
[origins]

	[origins."strictly:thief"]
		"strictly:strong" = true
		"origins:fragile" = true
		"origins:more_exhaustion" = true
		"strictly:money_lover" = true
		"strictly:night-owl" = true
		"strictly:superstealth" = true
		"origins:tailwind" = true
		enabled = true
		"strictly:cloak" = true
		"origins:shulker_inventory" = true

	[origins."strictly:birdofparadise"]
		"strictly:wet_wings" = true
		"strictly:claustrophobic_sleep" = true
		"origins:carnivore" = true
		"origins:launch" = true
		"origins:aerial_combatant" = true
		"origins:slow_falling" = true
		"origins:tailwind" = true
		"origins:light_armor" = true
		enabled = true
		"strictly:winged" = true

	[origins."origins:arachnid"]
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true
		"origins:master_of_webs" = true
		enabled = true
		"origins:climbing" = true

	[origins."strictly:plantaemancer"]
		"strictly:poison_ivy_vines" = true
		"strictly:flammable" = true
		"strictly:regrowth" = true
		"strictly:plant_caretaker" = true
		"strictly:blissful_light" = true
		enabled = true
		"strictly:light_deprivation" = true

	[origins."origins:feline"]
		"origins:cat_vision" = true
		"origins:velvet_paws" = true
		"origins:fall_immunity" = true
		"origins:weak_arms" = true
		"origins:nine_lives" = true
		enabled = true
		"origins:sprint_jump" = true
		"origins:scare_creepers" = true

	[origins."toomanyorigins:swarm"]
		"toomanyorigins:stinging_pains" = true
		"origins:arthropod" = true
		"toomanyorigins:unity" = true
		"toomanyorigins:beekeeper" = true
		"toomanyorigins:pollination" = true
		"toomanyorigins:hover" = true
		"toomanyorigins:calming_aura" = true
		enabled = true

	[origins."origins:shulk"]
		"origins:strong_arms" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true
		"origins:strong_arms_break_speed" = true
		"origins:natural_armor" = true
		enabled = true
		"origins:shulker_inventory" = true

	[origins."strictly:umvuthi"]
		"strictly:sun_strength" = true
		"strictly:sunblessing" = true
		"strictly:weak_health" = true
		"strictly:sun_block" = true
		enabled = true
		"strictly:vegetarian1" = true

	[origins."strictly:otter"]
		"origins:swim_speed" = true
		"origins:like_water" = true
		"strictly:miniature_dwarf" = true
		"strictly:land_slow" = true
		"origins:wet_eyes" = true
		"strictly:improved_lungs" = true
		enabled = true
		"strictly:heart_reduction" = true
		"origins:aquatic" = true
		"origins:no_shield" = true
		"origins:claustrophobia" = true
		"strictly:otter_gods_blessing" = true
		"strictly:aquatic_predator" = true
		"strictly:mini_riptide" = true
		"origins:aqua_affinity" = true
		"strictly:step_height" = true
		"strictly:otter_pouch" = true
		"strictly:jump" = true
		"origins:more_exhasution" = true

	[origins."origins:phantom"]
		"origins:phasing" = true
		"origins:fragile" = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:invisibility" = true
		"origins:hunger_over_time" = true
		enabled = true
		"origins:burn_in_daylight" = true
		"origins:phantomize_overlay" = true

	[origins."strictly:wildcat"]
		"strictly:nocturnal_eyes1" = true
		"strictly:feline_grace" = true
		"origins:carnivore" = true
		"strictly:feared_hunter" = true
		"strictly:water_weary" = true
		"strictly:soft_paws" = true
		enabled = true
		"origins:climbing" = true

	[origins."toomanyorigins:hisskin"]
		"toomanyorigins:buildup" = true
		"toomanyorigins:stubby_legs" = true
		"toomanyorigins:conductive" = true
		"toomanyorigins:aerial_stability" = true
		"toomanyorigins:redirect_lightning_chance" = true
		"toomanyorigins:ailurophobia" = true
		enabled = true

	[origins."origins:avian"]
		"origins:fresh_air" = true
		"origins:vegetarian" = true
		"origins:lay_eggs" = true
		"origins:slow_falling" = true
		"origins:tailwind" = true
		"origins:like_air" = true
		enabled = true

	[origins."toomanyorigins:withered"]
		"toomanyorigins:deathly_digestion" = true
		"toomanyorigins:unholy" = true
		"toomanyorigins:affliction" = true
		"origins:nether_spawn" = true
		"toomanyorigins:spirit_strider" = true
		enabled = true
		"toomanyorigins:soul_siphon" = true
		"toomanyorigins:hell_raised" = true

	[origins."strictly:adapted_raccoon"]
		"strictly:nocturnal_eyes1" = true
		"strictly:hates_carrots" = true
		"strictly:scurry" = true
		"strictly:thick_fur_cont" = true
		"strictly:tough_stomach" = true
		"strictly:trash_lover" = true
		"strictly:jump2" = true
		"strictly:rabies" = true
		"strictly:thick_fur" = true
		"strictly:expert_at_hiding" = true
		enabled = true
		"strictly:rabies_resistant" = true
		"strictly:small_body" = true
		"strictly:claustrophobia" = true
		"strictly:nocturnal" = true
		"strictly:small_hands" = true
		"strictly:rabies_cont" = true
		"strictly:tough_heart" = true
		"strictly:sharp_claws" = true
		"strictly:step_height" = true
		"strictly:arrow_weak" = true

	[origins."strictly:high_elf"]
		"strictly:flamethrower" = true
		"strictly:forest_vision" = true
		"strictly:jump3" = true
		"strictly:vegetarian" = true
		"strictly:falldmg" = true
		"strictly:hyper_sight" = true
		"strictly:spindly" = true
		enabled = true
		"strictly:towering" = true

	[origins."toomanyorigins:hare"]
		"origins:vegetarian" = true
		"toomanyorigins:frail" = true
		"toomanyorigins:hot_hops" = true
		"toomanyorigins:drenchable_fur" = true
		"toomanyorigins:cancel_out_sprint_disable_on_hit" = true
		"toomanyorigins:extra_step_height" = true
		"toomanyorigins:waterskipper" = true
		"toomanyorigins:prevent_movement_checks" = true
		enabled = true
		"toomanyorigins:superfall" = true
		"toomanyorigins:small_appetite" = true

	[origins."strictly:priest"]
		"origins:vegetarian" = true
		"strictly:holy_shield" = true
		"strictly:holy_curse" = true
		"strictly:scholar" = true
		"origins:ender_particles" = true
		"strictly:nimble" = true
		"origins:fall_immunity" = true
		enabled = true

	[origins."origins:enderian"]
		"origins:water_vulnerability" = true
		"origins:throw_ender_pearl" = true
		"origins:pumpkin_hate" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true
		enabled = true
		"origins:extra_reach" = true

	[origins."strictly:dwarf"]
		"strictly:nocturnal_eyes1" = true
		"strictly:potent_brew" = true
		"strictly:haste" = true
		"strictly:pickaxeless_stone" = true
		"strictly:dense" = true
		"strictly:miniature_dwarf" = true
		"strictly:insatiable_hunger" = true
		"strictly:gold_lover" = true
		"strictly:step_height" = true
		"strictly:jump" = true
		enabled = true

	[origins."toomanyorigins:dragonborn"]
		"toomanyorigins:block_synergistics" = true
		"toomanyorigins:zenith_scales" = true
		"toomanyorigins:rough_claws" = true
		"toomanyorigins:draconic_breath" = true
		"toomanyorigins:weaponry_pride" = true
		enabled = true

	[origins."origins:human"]
		enabled = true

	[origins."origins:merling"]
		"origins:air_from_potions" = true
		"origins:swim_speed" = true
		"origins:water_vision" = true
		"origins:like_water" = true
		"origins:aqua_affinity" = true
		"origins:water_breathing" = true
		"origins:conduit_power_on_land" = true
		enabled = true
		"origins:aquatic" = true

	[origins."strictly:troll"]
		"strictly:ravenous" = true
		"strictly:cunning_hidden" = true
		"strictly:lead_belly" = true
		"strictly:unweildy" = true
		"strictly:sluggish" = true
		"strictly:gargantuan" = true
		enabled = true
		"strictly:xxxl" = true
		"strictly:stocky" = true

	[origins."origins:blazeborn"]
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:fire_immunity" = true
		"origins:damage_from_snowballs" = true
		"origins:nether_spawn" = true
		"origins:damage_from_potions" = true
		enabled = true

	[origins."strictly:knight"]
		"strictly:book" = true
		"strictly:bowless" = true
		"strictly:skilled_swordsman" = true
		"strictly:valour" = true
		"strictly:burdened" = true
		"strictly:crescent_worship" = true
		"strictly:skofnung" = true
		enabled = true

	[origins."strictly:buzz"]
		"strictly:stinger" = true
		"strictly:itty_bitty" = true
		"strictly:freedom_calls" = true
		"strictly:new_diet" = true
		"strictly:bee_diet" = true
		"strictly:nectar_processing" = true
		"strictly:bee_skin" = true
		"strictly:smoke_sickness" = true
		enabled = true

	[origins."origins:elytrian"]
		"origins:more_kinetic_damage" = true
		"origins:elytra" = true
		"origins:claustrophobia" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:launch_into_air" = true
		enabled = true

	[origins."strictly:paladin"]
		"strictly:leech" = true
		"strictly:well_built" = true
		"strictly:book" = true
		"strictly:durendal" = true
		"strictly:holy_fire" = true
		"strictly:dried_out" = true
		"strictly:skilled_swordsman_1" = true
		enabled = true
		"strictly:praise_the_sun" = true

