
[origins]

	[origins."strictly:thief"]
		"strictly:strong" = true
		"origins:fragile" = true
		"origins:more_exhaustion" = true
		"strictly:money_lover" = true
		"strictly:night-owl" = true
		"strictly:superstealth" = true
		"origins:tailwind" = true
		enabled = true
		"strictly:cloak" = true
		"origins:shulker_inventory" = true

	[origins."strictly:birdofparadise"]
		"strictly:wet_wings" = true
		"strictly:claustrophobic_sleep" = true
		"origins:carnivore" = true
		"origins:launch" = true
		"origins:aerial_combatant" = true
		"origins:slow_falling" = true
		"origins:tailwind" = true
		"origins:light_armor" = true
		enabled = true
		"strictly:winged" = true

	[origins."origins:arachnid"]
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true
		"origins:master_of_webs" = true
		enabled = true
		"origins:climbing" = true

	[origins."strictly:plantaemancer"]
		"strictly:poison_ivy_vines" = true
		"strictly:flammable" = true
		"strictly:regrowth" = true
		"strictly:plant_caretaker" = true
		"strictly:blissful_light" = true
		enabled = true
		"strictly:light_deprivation" = true

	[origins."origins:feline"]
		"origins:cat_vision" = true
		"origins:velvet_paws" = true
		"origins:fall_immunity" = true
		"origins:weak_arms" = true
		"origins:nine_lives" = true
		enabled = true
		"origins:sprint_jump" = true
		"origins:scare_creepers" = true

	[origins."toomanyorigins:swarm"]
		"toomanyorigins:stinging_pains" = true
		"origins:arthropod" = true
		"toomanyorigins:unity" = true
		"toomanyorigins:beekeeper" = true
		"toomanyorigins:pollination" = true
		"toomanyorigins:hover" = true
		"toomanyorigins:calming_aura" = true
		enabled = true

	[origins."origins:shulk"]
		"origins:strong_arms" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true
		"origins:strong_arms_break_speed" = true
		"origins:natural_armor" = true
		enabled = true
		"origins:shulker_inventory" = true

	[origins."strictly:umvuthi"]
		"strictly:sun_strength" = true
		"strictly:sunblessing" = true
		"strictly:weak_health" = true
		"strictly:sun_block" = true
		enabled = true
		"strictly:vegetarian1" = true

	[origins."strictly:otter"]
		"origins:swim_speed" = true
		"origins:like_water" = true
		"strictly:miniature_dwarf" = true
		"strictly:land_slow" = true
		"origins:wet_eyes" = true
		"strictly:improved_lungs" = true
		enabled = true
		"strictly:heart_reduction" = true
		"origins:aquatic" = true
		"origins:no_shield" = true
		"origins:claustrophobia" = true
		"strictly:otter_gods_blessing" = true
		"strictly:aquatic_predator" = true
		"strictly:mini_riptide" = true
		"origins:aqua_affinity" = true
		"strictly:step_height" = true
		"strictly:otter_pouch" = true
		"strictly:jump" = true
		"origins:more_exhasution" = true

	[origins."origins:phantom"]
		"origins:phasing" = true
		"origins:fragile" = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:invisibility" = true
		"origins:hunger_over_time" = true
		enabled = true
		"origins:burn_in_daylight" = true
		"origins:phantomize_overlay" = true

	[origins."strictly:wildcat"]
		"strictly:nocturnal_eyes1" = true
		"strictly:feline_grace" = true
		"origins:carnivore" = true
		"strictly:feared_hunter" = true
		"strictly:water_weary" = true
		"strictly:soft_paws" = true
		enabled = true
		"origins:climbing" = true

	[origins."toomanyorigins:hisskin"]
		"toomanyorigins:buildup" = true
		"toomanyorigins:stubby_legs" = true
		"toomanyorigins:conductive" = true
		"toomanyorigins:aerial_stability" = true
		"toomanyorigins:redirect_lightning_chance" = true
		"toomanyorigins:ailurophobia" = true
		enabled = true

	[origins."origins:avian"]
		"origins:fresh_air" = true
		"origins:vegetarian" = true
		"origins:lay_eggs" = true
		"origins:slow_falling" = true
		"origins:tailwind" = true
		"origins:like_air" = true
		enabled = true

	[origins."toomanyorigins:withered"]
		"toomanyorigins:deathly_digestion" = true
		"toomanyorigins:unholy" = true
		"toomanyorigins:affliction" = true
		"origins:nether_spawn" = true
		"toomanyorigins:spirit_strider" = true
		enabled = true
		"toomanyorigins:soul_siphon" = true
		"toomanyorigins:hell_raised" = true

	[origins."strictly:adapted_raccoon"]
		"strictly:nocturnal_eyes1" = true
		"strictly:hates_carrots" = true
		"strictly:scurry" = true
		"strictly:thick_fur_cont" = true
		"strictly:tough_stomach" = true
		"strictly:trash_lover" = true
		"strictly:jump2" = true
		"strictly:rabies" = true
		"strictly:thick_fur" = true
		"strictly:expert_at_hiding" = true
		enabled = true
		"strictly:rabies_resistant" = true
		"strictly:small_body" = true
		"strictly:claustrophobia" = true
		"strictly:nocturnal" = true
		"strictly:small_hands" = true
		"strictly:rabies_cont" = true
		"strictly:tough_heart" = true
		"strictly:sharp_claws" = true
		"strictly:step_height" = true
		"strictly:arrow_weak" = true

	[origins."strictly:high_elf"]
		"strictly:flamethrower" = true
		"strictly:forest_vision" = true
		"strictly:jump3" = true
		"strictly:vegetarian" = true
		"strictly:falldmg" = true
		"strictly:hyper_sight" = true
		"strictly:spindly" = true
		enabled = true
		"strictly:towering" = true

	[origins."toomanyorigins:hare"]
		"origins:vegetarian" = true
		"toomanyorigins:frail" = true
		"toomanyorigins:hot_hops" = true
		"toomanyorigins:drenchable_fur" = true
		"toomanyorigins:cancel_out_sprint_disable_on_hit" = true
		"toomanyorigins:extra_step_height" = true
		"toomanyorigins:waterskipper" = true
		"toomanyorigins:prevent_movement_checks" = true
		enabled = true
		"toomanyorigins:superfall" = true
		"toomanyorigins:small_appetite" = true

	[origins."strictly:priest"]
		"origins:vegetarian" = true
		"strictly:holy_shield" = true
		"strictly:holy_curse" = true
		"strictly:scholar" = true
		"origins:ender_particles" = true
		"strictly:nimble" = true
		"origins:fall_immunity" = true
		enabled = true

	[origins."origins:enderian"]
		"origins:water_vulnerability" = true
		"origins:throw_ender_pearl" = true
		"origins:pumpkin_hate" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true
		enabled = true
		"origins:extra_reach" = true

	[origins."strictly:dwarf"]
		"strictly:nocturnal_eyes1" = true
		"strictly:potent_brew" = true
		"strictly:haste" = true
		"strictly:pickaxeless_stone" = true
		"strictly:dense" = true
		"strictly:miniature_dwarf" = true
		"strictly:insatiable_hunger" = true
		"strictly:gold_lover" = true
		"strictly:step_height" = true
		"strictly:jump" = true
		enabled = true

	[origins."toomanyorigins:dragonborn"]
		"toomanyorigins:block_synergistics" = true
		"toomanyorigins:zenith_scales" = true
		"toomanyorigins:rough_claws" = true
		"toomanyorigins:draconic_breath" = true
		"toomanyorigins:weaponry_pride" = true
		enabled = true

	[origins."origins:human"]
		enabled = true

	[origins."origins:merling"]
		"origins:air_from_potions" = true
		"origins:swim_speed" = true
		"origins:water_vision" = true
		"origins:like_water" = true
		"origins:aqua_affinity" = true
		"origins:water_breathing" = true
		"origins:conduit_power_on_land" = true
		enabled = true
		"origins:aquatic" = true

	[origins."strictly:troll"]
		"strictly:ravenous" = true
		"strictly:cunning_hidden" = true
		"strictly:lead_belly" = true
		"strictly:unweildy" = true
		"strictly:sluggish" = true
		"strictly:gargantuan" = true
		enabled = true
		"strictly:xxxl" = true
		"strictly:stocky" = true

	[origins."origins:blazeborn"]
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:fire_immunity" = true
		"origins:damage_from_snowballs" = true
		"origins:nether_spawn" = true
		"origins:damage_from_potions" = true
		enabled = true

	[origins."strictly:knight"]
		"strictly:book" = true
		"strictly:bowless" = true
		"strictly:skilled_swordsman" = true
		"strictly:valour" = true
		"strictly:burdened" = true
		"strictly:crescent_worship" = true
		"strictly:skofnung" = true
		enabled = true

	[origins."strictly:buzz"]
		"strictly:stinger" = true
		"strictly:itty_bitty" = true
		"strictly:freedom_calls" = true
		"strictly:new_diet" = true
		"strictly:bee_diet" = true
		"strictly:nectar_processing" = true
		"strictly:bee_skin" = true
		"strictly:smoke_sickness" = true
		enabled = true

	[origins."origins:elytrian"]
		"origins:more_kinetic_damage" = true
		"origins:elytra" = true
		"origins:claustrophobia" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:launch_into_air" = true
		enabled = true

	[origins."strictly:paladin"]
		"strictly:leech" = true
		"strictly:well_built" = true
		"strictly:book" = true
		"strictly:durendal" = true
		"strictly:holy_fire" = true
		"strictly:dried_out" = true
		"strictly:skilled_swordsman_1" = true
		enabled = true
		"strictly:praise_the_sun" = true

	[origins."medievalorigins:dwarf"]
		enabled = true
		"medievalorigins:dwarf/dwarven_tech" = true
		"medievalorigins:dwarf/miniature" = true
		"medievalorigins:dwarf/nocturnal_eyes" = true
		"medievalorigins:dwarf/darkness_dweller" = true
		"medievalorigins:dwarf/dense" = true
		"medievalorigins:dwarf/potent_brew" = true
		"medievalorigins:dwarf/mythril_resonance" = true
		"medievalorigins:dwarf/pickaxeless_stone" = true
		"medievalorigins:dwarf/helmet_spawn" = true

	[origins."medievalorigins:pixie"]
		enabled = true
		"medievalorigins:pixie/flight" = true
		"medievalorigins:pixie/pixie_properties" = true
		"medievalorigins:pixie/feather_footed" = true
		"medievalorigins:pixie/wings" = true
		"medievalorigins:pixie/mount" = true
		"medievalorigins:pixie/good_fortunes" = true
		"medievalorigins:pixie/mischief_maketh_man" = true
		"medievalorigins:pixie/curse_of_flight" = true
		"medievalorigins:pixie/troublemaker" = true

	[origins."medievalorigins:revenant"]
		enabled = true
		"medievalorigins:revenant/transfer_item" = true
		"medievalorigins:revenant/skeleton_summons" = true
		"medievalorigins:revenant/zombie_summons" = true
		"medievalorigins:revenant/putrid_communion" = true
		"medievalorigins:revenant/hellraiser" = true
		"medievalorigins:revenant/siphon" = true
		"medievalorigins:revenant/unwitherable" = true
		"medievalorigins:revenant/undeadge" = true
		"medievalorigins:revenant/poor_reputation" = true
		"medievalorigins:revenant/black_thumb" = true
		"medievalorigins:revenant/disturbed" = true
		"medievalorigins:revenant/unguarded" = true
		"origins_survive:sleepless" = true

	[origins."medievalorigins:gorgon"]
		enabled = true
		"medievalorigins:gorgon/petrifying_gaze" = true
		"medievalorigins:gorgon/revenge" = true
		"medievalorigins:gorgon/hydrophobe" = true
		"medievalorigins:gorgon/to_stone" = true
		"medievalorigins:gorgon/silver_aversion" = true
		"medievalorigins:gorgon/poison_blood" = true
		"medievalorigins:gorgon/poison_immune" = true
		"origins_env_deh:thirst_resistance" = true

	[origins."medievalorigins:fae"]
		enabled = true
		"medievalorigins:fae/levitation" = true
		"medievalorigins:fae/magic_resistance" = true
		"medievalorigins:fae/magic_damage_boost" = true
		"medievalorigins:fae/regen" = true
		"medievalorigins:fae/allure" = true
		"medievalorigins:fae/diminutive" = true
		"medievalorigins:fae/iron_aversion" = true

	[origins."medievalorigins:goblin"]
		enabled = true
		"medievalorigins:goblin/greedy" = true
		"medievalorigins:goblin/green" = true
		"medievalorigins:goblin/durability" = true
		"medievalorigins:goblin/cunning" = true
		"medievalorigins:goblin/nippy" = true
		"medievalorigins:goblin/stunted" = true
		"medievalorigins:goblin/frail" = true

	[origins."medievalorigins:siren"]
		enabled = true
		"medievalorigins:siren/amphibious" = true
		"medievalorigins:siren/siren_song" = true
		"medievalorigins:siren/holy_water" = true
		"medievalorigins:siren/out_of_your_depth" = true
		"medievalorigins:siren/flammable" = true
		"medievalorigins:siren/water_vision" = true
		"origins:aquatic" = true
		"origins:like_water" = true
		"medievalorigins:siren/seduce" = true
		"mermod:fabulous_fins" = true
		"origins_env_deh:water_dweller" = true
		"origins_env_deh:cold_resistance" = true
		"thermoo-patches:cold_immune" = true
		"survive:cold_blooded" = true

	[origins."medievalorigins:incubus"]
		enabled = true
		"medievalorigins:incubus/demon_fire" = true
		"medievalorigins:incubus/hellborne" = true
		"medievalorigins:incubus/carnivore" = true
		"medievalorigins:incubus/unholy_deal" = true
		"medievalorigins:incubus/hydrophobe" = true
		"medievalorigins:incubus/impure" = true
		"medievalorigins:incubus/dimension_strength" = true
		"medievalorigins:incubus/lava_swim" = true
		"medievalorigins:incubus/red" = true
		"medievalorigins:incubus/spell_power" = true
		"origins:nether_spawn" = true
		"origins_env_deh:heat_resistance" = true
		"thermoo-patches:heat_immune" = true
		"thermoo-patches:cold_vulnerability" = true
		"origins_survive:lava_drinker" = true
		"origins_survive:heat_resistance" = true
		"origins_toughasnails:lava_drinker" = true
		"origins_toughasnails:thermal_regulator" = true

	[origins."medievalorigins:alfiq"]
		enabled = true
		"medievalorigins:alfiq/clawed" = true
		"medievalorigins:alfiq/poor_grip" = true
		"medievalorigins:alfiq/agile_preference" = true
		"medievalorigins:alfiq/on_your_feet" = true
		"medievalorigins:alfiq/crepuscular" = true
		"medievalorigins:alfiq/pickpocket" = true
		"medievalorigins:alfiq/pickpocket_player" = true
		"medievalorigins:alfiq/pounce" = true
		"origins:carnivore" = true
		"origins:velvet_paws" = true
		"origins:scare_creepers" = true
		"medievalorigins:alfiq/meow" = true

	[origins."medievalorigins:troll"]
		enabled = true
		"medievalorigins:troll/ironhide" = true
		"medievalorigins:troll/ham_fisted" = true
		"medievalorigins:troll/mountainous" = true
		"medievalorigins:troll/apex_predator" = true
		"medievalorigins:troll/lumbering" = true
		"medievalorigins:troll/old_blood" = true
		"medievalorigins:troll/out_of_stock" = true
		"medievalorigins:troll/spell_power" = true
		"origins_env_deh:cold_resistance" = true
		"thermoo-patches:cold_immune" = true
		"origins_survive:cold_resistance" = true
		"origins_toughasnails:cold_resistance" = true

	[origins."medievalorigins:high_elf"]
		enabled = true
		"medievalorigins:high_elf/mystic_affinity" = true
		"medievalorigins:high_elf/mana_rpgmana" = true
		"medievalorigins:high_elf/blazenbreath_weak" = true
		"medievalorigins:high_elf/fragile" = true
		"medievalorigins:high_elf/blazenbreath" = true
		"medievalorigins:high_elf/mana_irons_ars" = true
		"medievalorigins:high_elf/towering" = true
		"medievalorigins:high_elf/extrusive_movement" = true
		"medievalorigins:high_elf/gear_spawn" = true
		"medievalorigins:high_elf/glacial_step" = true
		"medievalorigins:high_elf/elegant" = true
		"medievalorigins:high_elf/ebonbreath" = true
		"medievalorigins:high_elf/void_warp" = true
		"medievalorigins:high_elf/subclass_picker" = true

	[origins."medievalorigins:plague_victim"]
		enabled = true
		"medievalorigins:plague_victim/foul_aura" = true
		"medievalorigins:plague_victim/plague_immunity" = true
		"medievalorigins:plague_victim/undeadge" = true
		"medievalorigins:plague_victim/risk_of_transmission" = true
		"medievalorigins:plague_victim/contagious" = true
		"medievalorigins:plague_victim/insomniac" = true
		"medievalorigins:plague_victim/sensitive_skin" = true
		"medievalorigins:plague_victim/skin_and_bones" = true
		"medievalorigins:plague_victim/eternal_suffering" = true
		"origins_survive:illness_resistance" = true

	[origins."medievalorigins:valkyrie"]
		enabled = true
		"medievalorigins:valkyrie/wings" = true
		"medievalorigins:valkyrie/divine_smite" = true
		"medievalorigins:valkyrie/corruption" = true
		"medievalorigins:valkyrie/vanquisher" = true
		"medievalorigins:valkyrie/intervention" = true
		"medievalorigins:valkyrie/heavenly_implements" = true
		"medievalorigins:valkyrie/spell_power" = true

	[origins."medievalorigins:banshee"]
		enabled = true
		"medievalorigins:banshee/spectral" = true
		"medievalorigins:banshee/sonic_shriek" = true
		"medievalorigins:banshee/lunar_nexus" = true
		"medievalorigins:banshee/dimeritium_shackles" = true
		"medievalorigins:banshee/hexed" = true
		"medievalorigins:banshee/immaterial" = true
		"medievalorigins:banshee/cursed_sigil" = true
		"medievalorigins:banshee/cursed_ward" = true
		"origins_survive:sleepless" = true

	[origins."medievalorigins:wood_elf"]
		enabled = true
		"medievalorigins:wood_elf/empowered_shot_apotheosis" = true
		"medievalorigins:wood_elf/towering" = true
		"medievalorigins:wood_elf/gear_spawn" = true
		"medievalorigins:wood_elf/archer" = true
		"medievalorigins:wood_elf/graceful" = true
		"medievalorigins:wood_elf/elegant" = true
		"medievalorigins:wood_elf/forest_vision" = true
		"medievalorigins:wood_elf/steward" = true
		"medievalorigins:wood_elf/empowered_shot_zenith" = true
		"medievalorigins:wood_elf/eagle_eyed" = true
		"medievalorigins:wood_elf/spell_power" = true

	[origins."medievalorigins:moon_elf"]
		enabled = true
		"medievalorigins:moon_elf/moonlight_rogue" = true
		"medievalorigins:moon_elf/stealth" = true
		"medievalorigins:moon_elf/ethereal" = true
		"medievalorigins:moon_elf/crazed" = true
		"medievalorigins:moon_elf/elegant" = true
		"medievalorigins:moon_elf/nimble" = true
		"medievalorigins:moon_elf/fragile" = true
		"medievalorigins:moon_elf/towering" = true
		"origins_survive:sleepless" = true

	[origins."medievalorigins:yeti"]
		enabled = true
		"medievalorigins:yeti/frigid_pulse" = true
		"medievalorigins:yeti/from_whence_you_came" = true
		"medievalorigins:yeti/frosty_breath" = true
		"medievalorigins:yeti/titanic" = true
		"medievalorigins:yeti/unstoppable" = true
		"medievalorigins:yeti/winter_body" = true
		"medievalorigins:yeti/flammable" = true
		"medievalorigins:yeti/thick_fur" = true
		"medievalorigins:yeti/spell_power" = true
		"origins_env_deh:cold_resistance" = true
		"thermoo-patches:cold_immune" = true
		"origins_survive:cold_resistance" = true
		"origins_toughasnails:cold_resistance" = true

	[origins."medievalorigins:ogre"]
		enabled = true
		"medievalorigins:ogre/gargantuan" = true
		"medievalorigins:ogre/bloodlust" = true
		"medievalorigins:ogre/ravager" = true
		"medievalorigins:ogre/lead_belly" = true
		"medievalorigins:ogre/stocky" = true
		"medievalorigins:ogre/ravenous" = true
		"medievalorigins:ogre/sluggish" = true
		"medievalorigins:ogre/unwieldy" = true
		"medievalorigins:ogre/ogre_properties" = true
		"medievalorigins:ogre/bloodlust_camera" = true
		"origins_survive:illness_resistance" = true

	[origins."medievalorigins:arachnae"]
		enabled = true
		"medievalorigins:arachnae/climber" = true
		"medievalorigins:arachnae/many_eyes" = true
		"medievalorigins:arachnae/venomous_bite" = true
		"medievalorigins:arachnae/web_slinger" = true
		"medievalorigins:arachnae/bottomless_stomach" = true
		"medievalorigins:arachnae/brittle" = true
		"medievalorigins:arachnae/fragile_exoskeleton" = true
		"origins:master_of_webs" = true
		"origins:arthropod" = true

